name: Generate Snake

on:
  # Executa o workflow a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  # Permite executar o workflow manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório com o gráfico da cobrinha
      - name: Checkout
        uses: actions/checkout@v2

      # Configura Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Instala dependências
      - name: Install dependencies
        run: pip install matplotlib pandas

      # Gera e salva o gráfico da cobrinha
      - name: Generate snake animation
        run: |
          git clone https://github.com/Platane/snk.git
          cd snk
          python3 main.py --output ../snake.svg
      # Adiciona, comita e faz push do gráfico gerado
      - name: Commit and Push
        env:
          REPO: bergaminevinicius/bergaminevinicius
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add snake.svg
          git commit -m 'Generate snake.svg'
          git push
